In [2]:
import pandas

data = pandas.read_csv('Experience-Salary.csv')
features = data.columns

features, data

(Index(['exp(in months)', 'salary(in thousands)'], dtype='object'),
      exp(in months)  salary(in thousands)
 0         18.290293             16.521825
 1         17.023407             11.666234
 2         26.343613             23.167255
 3         19.105834             20.877145
 4         27.742516             23.166236
 ..              ...                   ...
 995       22.161741             24.666502
 996       32.266497             24.160270
 997       17.039030             19.903797
 998       25.222124             21.974413
 999       16.418028             19.634787
 
 [1000 rows x 2 columns])

In [6]:
import numpy as np

def reshape(arr):
    return np.array(arr).reshape(-1,1)

In [9]:
from sklearn.linear_model import LinearRegression

x, y = reshape(data[features[0]]), reshape(data[features[1]])

reg = LinearRegression(fit_intercept=True)
reg.fit(x, y)
pred = reg.predict(x)

reg.intercept_, reg.coef_, reg.score(x, y), pred

(array([5.19871856]),
 array([[0.82284666]]),
 0.6576711967581765,
 array([[20.24882536],
        [19.20637193],
        [26.87547297],
        [20.91989019],
        [28.02655563],
        [31.25923615],
        [16.87194932],
        [29.82886015],
        [32.22209514],
        [27.31179205],
        [39.35821682],
        [31.69535009],
        [33.78295173],
        [27.83928797],
        [26.39628385],
        [35.58259329],
        [24.73886029],
        [25.02396459],
        [18.4743638 ],
        [24.33201241],
        [26.28875744],
        [27.90861648],
        [24.05927269],
        [21.69817732],
        [25.75593559],
        [33.10856878],
        [41.77824664],
        [21.31526532],
        [20.43056258],
        [31.15266327],
        [31.2981268 ],
        [20.27829386],
        [22.76486832],
        [27.34157976],
        [33.94876688],
        [27.68757694],
        [22.77813139],
        [29.7047583 ],
        [18.15686222],
        [17.04509927],
        [28.6